### ISSUE TITLE
Context-aware Data and Task Placement

### ISSUE THREAD

**Issue by MarsXan** [Cloudslab/iFogSim#1]
First, thank you for your great sim. 
I'm working with your sim for a while for academic purposes. I have this question :
can we use your sim for Context-aware Data and Task Placement as in this article?

https://ieeexplore.ieee.org/document/8767386

**Comment by mgoudarzi90** [comment]
> First, thank you for your great sim.
> I'm working with your sim for a while for academic purposes. I have this question :
> can we use your sim for Context-aware Data and Task Placement as in this article?
> 
> https://ieeexplore.ieee.org/document/8767386

Dear MarsXan,

Yes, it is possible to implement all scheduling algorithms in this simulator, same as what was described in the above paper.

**Comment by MarsXan** [comment]
Thank you for your fast response
