### ISSUE TITLE
Periodicity and SelectivityModel in the Simulator

### ISSUE THREAD

**Issue by vyk1** [Cloudslab/iFogSim#11]
Greetings,

I have read the papers regarding iFogSim, but I would like to have a deeper explanation about how periodicity, selectivity models and migration work in the simulation:
1. In which cases would only one application edge be periodic? "Shouldn't" all the application edges be configured as periodic, since the whole environment depends on the sensors?
2. Could the selectivity model be read as a chance of losing the packet?
3. When a migration happens in an intracluster mobility scenario, does migration to the nearest fog node happen every time an edge device moves?
4. In the simulator, is it possible to change the migration policy for intercluster mobility scenarios; for example the broker of the requests to be another gateway instead of a proxy?

Thanks in advance.

**Comment by Samodhap** [comment]
Hi,
1. Periodic edges are used when application modules in the middle of the DAG ( not connected to the sensor directly) have to do periodic processing (eg: there may be scenarios where some modules analyse data accumulated for a fixed period of time and generate results periodically.) In other cases where modules process data from sensors, it is processed in an event-driven manner, where once each data packet (tuple) is received it is processed (processing time will depend on the resource availability of the device and resource contention among modules deployed within the same device). So you don't have to make them periodic specifically.
2. Yes.
3.  In current implementation yes, if the parent node changes a migration occur. But this is a bench mark. You can implement your own policy to replace this. (by updating logic in ClusteringController and LocationHandler)
4. Can you please explain this more ? if it's about migrating modules to gateway, yes you can design your policy to do that based on resource availability.

**Comment by vyk1** [comment]
Hello again,
thanks for the quick reply!

In the 4th question, I meant exactly that: instead of migrating modules to the parent node (proxy), if it would be possible to design a gateway-to-gateway manner, even in different clusters. Could you confirm it?

**Comment by Samodhap** [comment]
Hi, 
Yes. You have to implement your own policy as described in answer to Q3. 
Hope this helps. :)

**Comment by vyk1** [comment]
Hello,
thanks again!

I'll close this issue (:

**Comment by imene-gcm** [comment]
Hi, 

I am actually creating a topology using proxy servers and gateways. As described in the  reference article, the default number of gateways is 118 and the number of proxies is fixed to 12.

- Is it possible to modify the number of these devices? If yes, how to do that please?

Thank you in advance!
Imene.
