### ISSUE TITLE
cloudsim error message....

### ISSUE THREAD

**Issue by wogur0407** [Cloudslab/iFogSim#8]
When vrgameFog.java is executed, the following error message is displayed.....

Exception in thread "main" java.lang.Error: Unresolved compliation problems:
      Log cnanot be resolved
      Log cnanot be resolved
      The method getId() is undefined for the type FogBroker
      The method getId() is undefined for the type FogBroker
      The method getId() is undefined for the type FogBroker
      The method getName() is undefined for the type FogDevice
      The method getName() is undefined for the type FogDevice
      CloudSim cannot be resolved
      CloudSim cannot be resolved
      Log cnanot be resolved

**Comment by Samodhap** [comment]
Hi, 
This looks like an import issue. 
iFogSim uses the package org.cloudbus.cloudsim cloudSim capabilities and this could be a class path issue with the IDE used.  (You cab check if FogBroker class has compile errors for imports to identify this)
Hope this helps.
